### ISSUE TITLE
[Need investigate] Root component HMR works for babel but not for TypeScript?

### ISSUE THREAD

**Issue by Jack-Works** [Jack-Works/react-refresh-transformer#2]
reported in #1

**Comment by Ogg70** [comment]
Hi, I have exactly the same problem.
I described in more detail [here](https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/365#issuecomment-845850819).
As far as I understand, the problem is [here](https://github.com/Jack-Works/react-refresh-transformer/blob/main/typescript/src/core.ts#L297) (I could be wrong). This includes arrow function components that are not hooks. Unfortunately I have no experience with custom ts transformers.

**Comment by Jack-Works** [comment]
> As far as I understand, the problem is [here](https://github.com/Jack-Works/react-refresh-transformer/blob/main/typescript/src/core.ts#L297) (I could be wrong). This includes arrow function components that are not hooks. Unfortunately I have no experience with custom ts transformers.

This is introduced in 2.0.0. Can you try 1.1.1 to check if it get fixed?

**Comment by Ogg70** [comment]
> > As far as I understand, the problem is [here](https://github.com/Jack-Works/react-refresh-transformer/blob/main/typescript/src/core.ts#L297) (I could be wrong). This includes arrow function components that are not hooks. Unfortunately I have no experience with custom ts transformers.
> 
> This is introduced in 2.0.0. Can you try 1.1.1 to check if it get fixed?

I have checked, there is no problem in version 1.1.1.

**Comment by Jack-Works** [comment]
Ok so I'll revert be48fbeb66689552f7be783744f44869989c1507 because it's a wrong port to the upstream changes but I though there is no harm to keep it.

**Comment by Jack-Works** [comment]
I have published 2.0.1, please try that out!

**Comment by Ogg70** [comment]
Unfortunately, these edits did not fix the problem.
I have prepared a [PR](https://github.com/Jack-Works/react-refresh-transformer/pull/6), please see.

**Comment by Jack-Works** [comment]
I tried to reproduce this and found it's likely not a bug in `react-refresh-transformer`.

If `used as entry component` means the following code:

```jsx
import { render } from 'react-dom'
import { Component } from './Component'

export function App() {
    return (
        <div>
            <Component />
        </div>
    )
}
render(<App />, document.getElementById('root')!)
```

Yes, in this case, it won't refresh but reload the whole tree. Because every time this file getting HMRed, this whole file will be re-executed. And if you re-call `ReactDOM.render` (the last line) on your root component, it will be unmounted and remounted, because the previous `App` has a different identity than the current `App`, and the reconciliation algorithms will not diff the vDOM tree for a different component tree.

If it is your case, please move `App` to another file, that will fix the problem. If not, please point out and give a reproduce. Thanks
